name: dotnet tests and coverage

on:
  push:
    branches:
      - '**'
      - '!main'
  pull_request:
    branches:
      - '**'
      - '!main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 1

        - uses: actions/setup-dotnet@v4
          with:
            dotnet-version: '9.x'

          run: dotnet restore

        - name: build
          run: for f in $(find . -name "*.sln"); do dotnet build $f; done
        - name: test
          run: for f in $(find . -name "*.sln"); do |
            dotnet test --collect:"XPlat Code Coverage"
            reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport -reporttypes:Html
        
        - uses: actions/upload-artifact@v4
          with:
            name: coverage-report
            path: coveragereport

